### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by robson-gomes** [Alessandro018/Eis-aQuestao#11]
Eu **como** desenvolvedor **quero** estudar o funcionamento das migrations **para**  utilizar no projeto.

**Comment by gabrielpessoa** [comment]
Esse explica melhor mais e o básico [Migrations Básico](https://imasters.com.br/back-end/desenvolvendo-migrations-utilizando-laravel).

Esse tem tudo [Documentação Migrations](https://laravel.com/docs/5.8/migrations).

**Comment by ricardomlp** [comment]
Explica tudo sobre gerar, executar, reversão e estrutura de migrações. Criação de tabelas, verificação, conexão com o bd, renomear e descartar tabelas, criação de colunas, tipos, modificações dos tipos, atualizando atributos, renomeando e eliminando colunas. Criação de índices, tipos de índices, renomeando e eliminando índices.:
https://laravel.com/docs/5.8/migrations

Criar Models e Migrations no Laravel:
https://www.youtube.com/watch?v=A1qHjtHdhBU

Laravel para iniciantes - Banco de dados e Migrations:
https://www.youtube.com/watch?v=22MQlLkZ9U8
