### ISSUE TITLE
Autenticação

### ISSUE THREAD

**Issue by Alessandro018** [Alessandro018/Eis-aQuestao#15]
Eu **como** desenvolvedor **quero** estudar mecanismo de autenticação no laravel **para** utilizar no sistema

**Comment by geovanejose** [comment]
[Autenticação no Laravel](https://laravel.com/docs/5.8/authentication)

**Comment by Alessandro018** [comment]
[Link alternativo](https://laravel-docs-pt-br.readthedocs.io/en/latest/authentication/#protegendo-rotas)

**Comment by Alessandro018** [comment]
The end :D

**Comment by Alessandro018** [comment]
The end :walking_man:
