### ISSUE TITLE
Protótipo do Front-end

### ISSUE THREAD

**Issue by Alessandro018** [Alessandro018/Eis-aQuestao#17]
Eu **como** desenvolvedor **quero** um protótipo da interface **para**  ter uma ideia de como ficaria o site

**Comment by AlexpGuedes** [comment]
[Protótipo do layout no Google Drive](https://drive.google.com/drive/folders/1-ZFYklALWM02--Y7GrL8APEnfSc7Dja2?usp=sharing)

**Comment by AlexpGuedes** [comment]
Imagens do protótipo.


![index](https://user-images.githubusercontent.com/48127413/65450918-91e61d00-de14-11e9-9dc6-a5c04bb916fd.png)




![login](https://user-images.githubusercontent.com/48127413/65450919-927eb380-de14-11e9-89a1-c928ce20e08f.png)





![cadastro](https://user-images.githubusercontent.com/48127413/65450921-927eb380-de14-11e9-8520-f757f1b625e4.png)
