### ISSUE TITLE
Estudar mecanismo de importação de estudantes

### ISSUE THREAD

**Issue by ranierivalenca** [Alessandro018/Eis-aQuestao#20]

**Comment by Alessandro018** [comment]
[Link 1](https://freek.dev/506-processing-a-csv-file-in-laravel)
[Link 2](https://daveismyname.blog/laravel-import-large-csv-file)
[Vídeo](https://www.youtube.com/watch?v=PrjuwU-Xu7A)

**Comment by Alessandro018** [comment]
**Links para importação xls / xlsx**

[Documentação Laravel Excel](https://docs.laravel-excel.com/3.1/imports/)
[Vídeo](https://www.youtube.com/watch?v=mMhjpRLq76I)
