### ISSUE TITLE
Povoar tabelas

### ISSUE THREAD

**Issue by ranierivalenca** [Alessandro018/Eis-aQuestao#21]
Eu **como** desenvolvedor **quero** preencher as tabelas com dados **para** o desenvolvimento do sistema.

**Comment by lilialnas** [comment]
https://portal.ifpe.edu.br/campus/igarassu/cursos/tecnicos/subsequente/logistica/matriz-curricular

**Comment by lilialnas** [comment]
https://portal.ifpe.edu.br/campus/igarassu/cursos/tecnicos/subsequente/informatica-para-internet/matriz-curricular

**Comment by ranierivalenca** [comment]
As tabelas `Professor` e `Estudante` deveriam ter mais dados (uns 20 professores e uns 100 estudantes, no mínimo).

Falta povoar os relacionamentos.
