### ISSUE TITLE
Seeders no Laravel

### ISSUE THREAD

**Issue by robson-gomes** [Alessandro018/Eis-aQuestao#23]
Eu **como** desenvolvedor **quero** aprender os mecanismos de Seeder **para** utilizar este recurso na manipulação do banco de dados.

**Comment by robson-gomes** [comment]
**Criando uma Seeder:**
- https://blog.especializati.com.br/seeders-no-laravel/

**Comment by siilvatamires** [comment]
O Laravel inclui um método simples de propagar seu banco de dados com dados de teste usando classes seed. Todas as classes de seed são armazenadas no diretório  database/seeds. As classes de seed podem ter qualquer nome que você desejar, mas provavelmente devem seguir alguma convenção sensata, como UsersTableSeeder, etc. [Link que explica o que é, e como utilizar .](https://laravel.com/docs/5.8/seeding)
