### ISSUE TITLE
Back-end de elaboração de provas

### ISSUE THREAD

**Issue by robson-gomes** [Alessandro018/Eis-aQuestao#3]
Eu **como** professor **quero** um sistema **para** facilitar a elaboração de provas e ter um controle maior tanto no aprendizado do aluno, quanto na questão da cola por aquele aluno que não estudou, pois cada prova será gerada de forma individual.

**Comment by ricardomlp** [comment]
Os Professores ou instituições que têm muitas turmas de um mesmo curso precisam garantir a originalidade das provas, e medir o aprendizado de seus alunos.

E importante que a geração das provas professor visualize um histórico completo de quantas vezes essa questão foi utilizada e em quais ocasiões. Assim, ele pode medir e verificar se os avaliados já entraram em contato com a questão anteriormente.

Durante o planejamento da avaliação o professor define quais regras serão aplicadas para a criação da prova: quantas questões, seu nível de dificuldade, o conteúdo, se são questões discursivas ou objetivas.

**Comment by lilialnas** [comment]
Está gerando no banco de dados, porém não é mostrada no front-end para o usuário
