### ISSUE TITLE
Estudo de CRUD em laravel

### ISSUE THREAD

**Issue by Alessandro018** [Alessandro018/Eis-aQuestao#30]
Eu **como** desenvolvedor **quero** estudar crud em laravel **para** criar cruds no nosso sistema

**Comment by geovanejose** [comment]
[](url)
[](url)

**Comment by geovanejose** [comment]
**Tutoriais de cruds no laravel 6**
[crud 1](https://itsolutionstuff.com/post/laravel-6-crud-application-tutorialexample.html)
[crud 2](https://appdividend.com/2019/09/12/laravel-6-crud-example-laravel-6-tutorial-for-beginners/)
[crud 3](https://www.mynotepaper.com/laravel-6-crud-create-read-update-delete-from-scratch.html)
[crud 4,com Ajax](https://w3path.com/laravel-6-create-first-ajax-crud-application-from-scratch/)

**Comment by geovanejose** [comment]
crud 3 criado

**Comment by geovanejose** [comment]
**Crud com Ajax criado**
[github do crud](https://github.com/geovanejose/Crud-no-Laravel)
[Tutorial do crud que fiz](https://itsolutionstuff.com/post/laravel-6-ajax-crud-tutorialexample.html)
