### ISSUE TITLE
CRUD de questões

### ISSUE THREAD

**Issue by Alessandro018** [Alessandro018/Eis-aQuestao#31]
Eu **como** professor **quero** cadastrar questões **para** gerar prova personalizada para cada aluno.

**Comment by lilialnas** [comment]
Ajustes a serem realizados no CRUD de questões
- [ ] Campo "Tipo" deve ser solicitado no cadastro da questão
- [ ] Combobox "Disciplina" deve ter o primeiro item como "Selecione"
- [ ] Na ação de edição da questão, não está trazendo a informação de Tipo e Disciplina.
- [ ] Modificar o nome do campo "Deletar" para "Excluir"
- [ ] Adicionar mensagem de confirmação de exclusão (Deseja excluir a questão?) na ação de excluir.
- [ ] Campo "Descrição da questão" deve limitar a quantidade de caracteres.
- [ ] Na listagem das questões, a descrição da questão deve ser adaptada ao tamanho da listagem.
