### ISSUE TITLE
Estudo sobre views no laravel

### ISSUE THREAD

**Issue by Alessandro018** [Alessandro018/Eis-aQuestao#34]
Eu **como** desenvolvedor **quero** estudar os mecanismos das views **para** utilizar este recurso em nosso projeto.

**Comment by robson-gomes** [comment]
**Creating Views:**

- https://laravel.com/docs/6.x/views

**Comment by siilvatamires** [comment]
Tutorial simple View:

•  https://youtu.be/_qwAK5TxXww

**Comment by siilvatamires** [comment]
[Laravel 6.0 create View ](https://youtu.be/MwTs_ujIVuo)
