### ISSUE TITLE
Estudo sobre múltipla autenticação no laravel

### ISSUE THREAD

**Issue by Alessandro018** [Alessandro018/Eis-aQuestao#39]
Eu **como** desenvolvedor **quero**  usuários com diferentes níveis de acesso **para** melhor gerenciamento do sistema.

**Comment by Alessandro018** [comment]
[Múltipla autenticação](https://hdtuto.com/article/laravel-57-multiple-authentication-example)

[Link alternativo](https://medium.com/@daluamon/multipla-autentica%C3%A7%C3%A3o-laravel-32711ca9bced)

[Vídeo parte 1](https://www.youtube.com/watch?v=CY2jlYgWTF4)

[Vídeo parte 2](https://www.youtube.com/watch?v=z-TJUpr1zRQ)

**Comment by ricardomlp** [comment]
Usuários e Controle de Acesso no Laravel.
Fontes de pesquisa sobre a questão:
http://blog.thiagobelem.net/como-criar-um-sistema-de-login-com-niveis-de-permissao, https://magazine.softerize.com.br/tutoriais/php/laravel/usuarios-e-controle-de-acesso-laravel, 
https://www.youtube.com/watch?v=Ia1oj1_-BzA, https://www.youtube.com/watch?v=FNu3gEd5z5Y.
Exemplo de código:
[auth.txt](https://github.com/Alessandro018/Eis-aQuestao/files/3727289/auth.txt)
