### ISSUE TITLE
Hospedagem no heroku 

### ISSUE THREAD

**Issue by gabrielpessoa** [Alessandro018/Eis-aQuestao#5]
Eu **como** desenvolvedor **quero** analisar como hospedar o projeto em laravel no heroku.

**Comment by geovanejose** [comment]
[Estudo da hospedagem no Heroku](https://cafecomdev.blogspot.com/2017/06/hospedando-aplicacao-php-com-laravel-no.html)

**Comment by ricardomlp** [comment]
#5 Hospedagem no heroku:
Deploy de uma aplicação laravel no heroku - > https://gist.github.com/trgomes/b99b27439451a74a8501ea896ba000c4

Como criar um projeto Laravel e fazer um deploy no heroku - > https://steemit.com/pt/@tiagoferezin/como-criar-um-projeto-laravel-e-fazer-um-deploy-no-heroku

https://www.youtube.com/watch?v=639Pe0PpVLQ,

https://blog.schoolofnet.com/fazendo-deploy-do-laravel-5-no-heroku/,

**Comment by geovanejose** [comment]
**Conta criada no Heroku**
