### ISSUE TITLE
Gerar PDF no Laravel

### ISSUE THREAD

**Issue by geovanejose** [Alessandro018/Eis-aQuestao#58]
Eu **como** desenvolvedor **quero** estudar como gerar PDF  no laravel **para**  criar provas.

**Comment by geovanejose** [comment]
[Gerando Pdf no laravel](https://blog.especializati.com.br/gerar-pdf-no-laravel-com-dompdf/)
[ Gerar Pdf no laravel](https://pt.stackoverflow.com/questions/188222/gerador-de-pdf-com-framework-laravel)

**Comment by geovanejose** [comment]
**PDF gerado com sucesso!!**

**Comment by robson-gomes** [comment]
[Gerando PDF com Laravel em 10 minutos](url)
