### ISSUE TITLE
Gerar PDF das provas criadas 

### ISSUE THREAD

**Issue by geovanejose** [Alessandro018/Eis-aQuestao#60]
Eu **como** Professor **quero** gerar os PDFs das provas **para** levar a impressão

**Comment by ricardomlp** [comment]
CONVERTENDO HTML PARA PDF COM PHP E DOMPDF | PHP TIPS - https://www.youtube.com/watch?v=mie9pKtAszo.

Como gerar PDF com PHP utilizando o dompdf - https://www.youtube.com/watch?v=PyCbo641nnM.

**Comment by ricardomlp** [comment]
Como gerar PDF com PHP utilizando o dompdf - https://www.youtube.com/watch?v=PyCbo641nnM
[gerar_pdf_com_dompdf.zip](https://github.com/Alessandro018/Eis-aQuestao/files/3884959/gerar_pdf_com_dompdf.zip)

**Comment by ricardomlp** [comment]
CONVERTENDO HTML PARA PDF COM PHP E DOMPDF | PHP TIPS - https://www.youtube.com/watch?v=mie9pKtAszo

**Comment by ranierivalenca** [comment]
A principal funcionalidade não está implementada. Vou ver o que consigo fazer sobre isso hoje
