### ISSUE TITLE
Alterações no front-end do cadastro de questões

### ISSUE THREAD

**Issue by robson-gomes** [Alessandro018/Eis-aQuestao#63]
Eu **como** professor **quero** uma interface simples e amigável **para**  fazer o cadastro de questões.

**Comment by lilialnas** [comment]
- [  ] Implementar todas as validações de campo. Limitar a quantidade de caracteres no cadastro da pergunta da questão.
- [  ] Centralizar os campos na tela do sistema. Não deixar esticado para ocupar toda tela.
- [  ] Exibir mensagem para o usuário tanto no sucesso do cadastro da questão quanto na falha. O usuário precisa ter o feedback das ações realizadas.

**Comment by lilialnas** [comment]
![draft_Cadastro de questão](https://user-images.githubusercontent.com/45184669/68219673-21125300-ffc5-11e9-8df1-4209bda84c08.png)
