### ISSUE TITLE
Paginação no laravel

### ISSUE THREAD

**Issue by siilvatamires** [Alessandro018/Eis-aQuestao#64]
Eu **como** desenvolvedor **quero** estudar paginação no laravel **para** implementar no projeto.

**Comment by siilvatamires** [comment]
[Introdução e uso básico](https://laravel.com/docs/5.8/pagination)

**Comment by siilvatamires** [comment]
[Paginação com laravel tutorial](https://youtu.be/Ul74JOXl7nc)

**Comment by siilvatamires** [comment]
[Laravel 6 pagination example](https://www.itsolutionstuff.com/post/laravel-6-pagination-example-tutorialexample.html
)

**Comment by geovanejose** [comment]
[Paginação com solicitação ajax usando Laravel e Vue](https://codeburst.io/pagination-with-ajax-request-using-laravel-and-vue-fc584b6fa1ea)

**Comment by geovanejose** [comment]
**Paginação de Questões criada!**
