### ISSUE TITLE
Definir esquema de cores do site

### ISSUE THREAD

**Issue by robson-gomes** [Alessandro018/Eis-aQuestao#65]
Eu **como** desenvolvedor **quero** estudar sobre esquema de cores **para** definir o padrão de cores do nosso site.

**Comment by robson-gomes** [comment]
[Como selecionar o esquema de cores perfeito para seu site](https://agenciaimma.com.br/como-selecionar-o-esquema-de-cores-perfeito-para-seu-site/url)

**Comment by robson-gomes** [comment]
Essas são algumas ferramentas que podemos utilizar para criar o esquema de cores ideal do nosso site. [ferramentas](uhttp://rodrigoamaral.net/2013/07/22/8-ferramentas-para-acertar-na-escolha-das-cores-do-seu-site/rl)

**Comment by robson-gomes** [comment]
[Ferramentas](http://rodrigoamaral.net/2013/07/22/8-ferramentas-para-acertar-na-escolha-das-cores-do-seu-site/url)

**Comment by ricardomlp** [comment]
Para compor o padrão de cores do nosso site, busquei entender como a psicologia das cores funciona, e como nosso cérebro se comporta diante de informações captadas visualmente.

As cores utilizadas nos anúncios geram emoções, impactando a pessoa que as recebe de maneira positiva ou negativa. As grandes marcas do mercado têm mostrado que essa pode ser sim uma técnica importante.

No desenvolvimento de nosso software, as cores podem alterar o humor e influenciar decisões.
![Psicologia-das-cores-significados-1](https://user-images.githubusercontent.com/42875766/68550791-071da980-03e5-11ea-889a-043aec0623d2.jpg)

podemos usar uma dessas ferramentas:

https://blog.wedologos.com.br/empreendedorismo/expandir-negocio/7-ferramentas-que-vao-lhe-ajudar-a-escolher-a-cor-certa-para-seu-projeto

https://www.impacta.com.br/blog/2014/06/13/13-ferramentas-para-escolher-o-esquema-de-cores-perfeito-parte-i

https://neilpatel.com/br/blog/esquema-de-cores-em-site

**Comment by geovanejose** [comment]
[Esquema de cores em site ](https://neilpatel.com/br/blog/esquema-de-cores-em-site/)

**Comment by siilvatamires** [comment]
Adicionando nova paleta de cores:

![NEW](https://user-images.githubusercontent.com/48129117/69111408-42ab1a00-0a5c-11ea-878d-cb306dab5ab5.jpg)
