### ISSUE TITLE
Logomarca do projeto

### ISSUE THREAD

**Issue by GuilhermeH6** [Alessandro018/Eis-aQuestao#68]
**Como** desenvolvedor **quero** uma logomarca **para** o site.

**Comment by GuilhermeH6** [comment]
Alguns protótipos de logomarca:
[logomarcas.zip](https://github.com/Alessandro018/Eis-aQuestao/files/3838476/logomarcas.zip)

**Comment by robson-gomes** [comment]
Algumas imagens que também podem ser utilizadas na criação da logomarca do site:

![1](https://user-images.githubusercontent.com/48128957/68720301-8a79ff00-058d-11ea-9e2c-cfe0465634e4.jpeg)

**Comment by robson-gomes** [comment]
![2](https://user-images.githubusercontent.com/48128957/68720323-9960b180-058d-11ea-891f-8f7121387dd5.jpeg)

**Comment by robson-gomes** [comment]
![3](https://user-images.githubusercontent.com/48128957/68720345-a7163700-058d-11ea-80eb-117d88974c99.png)

**Comment by ricardomlp** [comment]
![mlogo2](https://user-images.githubusercontent.com/42875766/68771504-e7fe6200-0606-11ea-8d79-31167800fdda.jpg)

**Comment by ricardomlp** [comment]
![charadainterrogaco](https://user-images.githubusercontent.com/42875766/68833447-3b69c200-0692-11ea-853d-bc1824dcd15f.jpg)

**Comment by ricardomlp** [comment]
![homem-interrigacao-bz](https://user-images.githubusercontent.com/42875766/68970623-740ab800-07c6-11ea-80d1-1a8e43520b40.png)

**Comment by GuilhermeH6** [comment]
Mais algumas logos:
[logo2.zip](https://github.com/Alessandro018/Eis-aQuestao/files/3856043/logo2.zip)

**Comment by Alessandro018** [comment]
Essa foi a logomarca selecionada
![Sem título-1](https://user-images.githubusercontent.com/42873829/69108136-89941200-0a52-11ea-9372-29850fede40a.jpg)

**Comment by GuilhermeH6** [comment]
As logos definitivas, incluindo a do footer e em formato png:

[LOGOS.zip](https://github.com/Alessandro018/Eis-aQuestao/files/3883064/LOGOS.zip)
