### ISSUE TITLE
Criar as entidades e relacionamentos

### ISSUE THREAD

**Issue by gabrielpessoa** [Alessandro018/Eis-aQuestao#7]
Eu **como** desenvolvedor **quero** criar o modelo ER  **para** implementar o sistema.

**Comment by Alessandro018** [comment]
[Modelo ER](https://drive.google.com/open?id=12J70cOhg1xJflaLcGJHbHI3vf1eL1-Bq)

**Comment by Alessandro018** [comment]
Inicialmente, esse será nosso modelo

**Comment by ranierivalenca** [comment]
Alguns relacionamentos já discutidos não estão neste modelo... Mesmo que seja um modelo inicial, não dá pra trabalhar sem o relacionamento entre disciplina e questão.

**Comment by Alessandro018** [comment]
![modelo](https://user-images.githubusercontent.com/42873829/65818567-0c35e900-e1e9-11e9-84f8-d2d6c77867d3.png)
