### ISSUE TITLE
Colocar formulário de cadastro de questões em um modal.

### ISSUE THREAD

**Issue by filipeandrev** [Alessandro018/Eis-aQuestao#77]
Na sessão de questões devem conter o formulário de cadastro de questões(em um modal). Quando uma questão for cadastrada esta deve aparecer na própria página de questões.

- [x] Colocar formulário em um modal.
- [x] Fazer os ajustes para que as questões sejam vistas na sessão de questões;

**Comment by geovanejose** [comment]
**"Mantendo o padrão das páginas",essa seria a mensagem de commit ):**

**Comment by lilialnas** [comment]
Alguns ajustes que devem ser feitos.

- [ ] Nível e Disciplina devem ser requisitados na ação de salvar.
- [ ] CTRL+ENTER para salvar as questões.
- [ ] Implementar cintura da página como um todo.
- [ ] Editar questão utilizando o mesmo modal do [+ nova questão]
- [ ] Colocar botão [ Cancelar] na ação de editar a questão
- [ ] Implementar breadcrumbs na edição da questão
- [ ] Paginação centralizada após o grid de questões

**Comment by geovanejose** [comment]
**Issue  será reaberta para fazermos estes ajustes acima!**
