### ISSUE TITLE
Melhorar o front-end da página welcome

### ISSUE THREAD

**Issue by robson-gomes** [Alessandro018/Eis-aQuestao#85]
**Como** desenvolvedor **quero** melhorar o front-end da página welcome **para** deixar a página com um layout mais organizado e fácil de navegar.

**Comment by K0rgana** [comment]
### Prototipação da tela de welcome 
![image](https://user-images.githubusercontent.com/48961500/69292382-c3951d80-0be4-11ea-9ef1-00a10309f980.png)

- atenção aos comentarios sobre as imagens do carousel e logo, que estão no lado direito do print

### Sobre as cores

1. Codigo da cor laranja (#ED9C2E)
2. Codigo da cor preta/cinza do footer (#343A40)

**[Link para ver o prototipo no Figma](https://www.figma.com/file/h5Ra6RnojXpYQLO2XN0qeH/eisaQuestao?node-id=2%3A3)**

**Comment by K0rgana** [comment]
### Tela de Questões
![image](https://user-images.githubusercontent.com/48961500/69394321-76837b00-0cba-11ea-8985-bf7d5f2039b5.png)

### Tela/Modal de criar questão
![image](https://user-images.githubusercontent.com/48961500/69393994-7cc52780-0cb9-11ea-822b-4ffa71ffca2f.png)

**Comment by siilvatamires** [comment]
• Sugestão de imagem para o carrossel


![images (3)](https://user-images.githubusercontent.com/48129117/69589950-a7222800-0fcc-11ea-97fa-ec40ab54f99e.jpeg)

**Comment by robson-gomes** [comment]
![Captura de tela de 2019-11-19 11-11-44](https://user-images.githubusercontent.com/48128957/69599472-e57b0f80-0feb-11ea-8789-1a4be517679a.png)

**Comment by siilvatamires** [comment]
• Sugestão de imagem para o carrossel 

![images (4)](https://user-images.githubusercontent.com/48129117/69894245-d356e500-12fb-11ea-82e7-4ff2a4c33e74.png)
