### ISSUE TITLE
Brainstorming

### ISSUE THREAD

**Issue by gabrielpessoa** [Alessandro018/Eis-aQuestao#9]
Fazer pesquisa com vários alunos no intervalo.

[Perguntas](https://docs.google.com/document/d/1u4ldUPsJUiGm0lXu21fbz_68des9uVc87I8EVbu9iK0/edit?usp=sharing)

**Comment by siilvatamires** [comment]
Criando formulário no google forms para realizar a pesquisa com alguns alunos.

**Comment by siilvatamires** [comment]
[Resultado da pesquisa que foi realizada com a participação de alguns alunos](https://docs.google.com/forms/d/e/1FAIpQLSdH1__Da-GT8YWxbyurDb2gd7QpSbwPkgXhz43BF-kFUOXJZg/viewanalytics)
